tests:
  - name: nginx_log
    inputs:
      - insert_at: kubernetes_source_remapper
        type: log
        log_fields:
          message: '10.42.2.170 - - [26/Mar/2025:12:43:34 +0000] "POST /loki/api/v1/push HTTP/1.1" 500 0 "-" "canary-push/3.4.2"'
          kubernetes:
            container_image: "grafana/loki:2.5.0"
            container_name: "nginx"
            pod_name: "loki-0"
            pod_namespace: "monitoring"
            pod_node_name: "node-1"
            node_labels:
              "topology.rook.io/chassis": "rack-1"
            pod_labels:
              "app.kubernetes.io/name": "loki"
              "app.kubernetes.io/component": "gateway"
              "app.kubernetes.io/instance": "loki"
    outputs:
      - extract_from: final
        conditions:
          - .labels.level == "error"
          - .labels.service_name == "loki"
  - name: loki_log
    inputs:
      - insert_at: kubernetes_source_remapper
        type: log
        log_fields:
          message: "ts=2025-03-26T14:01:03.428285248Z caller=spanlogger.go:111 table-name=loki_index_20173 user-id=fake user=fake caller=log.go:168 level=error msg=\"failed to init user index set\" err=\"RequestError: send request failed\\ncaused by: Get \\\"http://monitoring-loki.10.0.0.102:7480/?delimiter=%2F&list-type=2&prefix=index%2Floki_index_20173%2Ffake%2F\\\": dial tcp: lookup monitoring-loki.10.0.0.102 on 10.43.0.10:53: no such host\""
          kubernetes:
            container_image: "grafana/loki:2.5.0"
            container_name: "loki"
            pod_name: "loki-0"
            pod_namespace: "monitoring"
            pod_node_name: "node-1"
            node_labels:
              "topology.rook.io/chassis": "rack-1"
            pod_labels:
              "app.kubernetes.io/name": "loki"
              "app.kubernetes.io/component": "backend"
              "app.kubernetes.io/instance": "loki"
    outputs:
      - extract_from: final
        conditions:
          - .labels.level == "error"
          - .data.loki."user-id" == "fake"
          - .labels.service_name == "loki"
  - name: arr_log
    inputs:
      - insert_at: kubernetes_source_remapper
        type: log
        log_fields:
          message: "[Error] DownloadedMovieImportService: Import failed, path does not exist or is not accessible by Radarr: /media/downloads/completed/Spider-Man.Across.The.Spider-Verse.2023.REAL.HDR.2160p.WEB.h265-ETHEL/. Ensure the path exists and the user running Radarr has the correct permissions to access this file/folder"
          kubernetes:
            container_image: "radarr:0.0.1"
            container_name: "radarr"
            pod_name: "radarr-0"
            pod_namespace: "default"
            pod_node_name: "node-1"
            node_labels:
              "topology.rook.io/chassis": "rack-1"
            pod_labels:
              "app.kubernetes.io/name": "radarr"
              "app.kubernetes.io/instance": "radarr"
    outputs:
      - extract_from: final
        conditions:
          - .labels.level == "error"
          - .labels.service_name == "radarr"
          - contains(string!(.message), "not accessible by Radarr")
